# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/service.proto\x12\x0c\x65sgReporting\"(\n\x10UploadCSVRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\"4\n\x11UploadCSVResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"1\n\x18GenerateEsgReportRequest\x12\x15\n\rfacility_name\x18\x01 \x01(\t\"\xe9\x01\n\tStatsData\x12\x15\n\rfacility_name\x18\x01 \x01(\t\x12\x1e\n\x16total_annual_emissions\x18\x02 \x01(\x01\x12\x1d\n\x15mean_annual_emissions\x18\x03 \x01(\x01\x12\x1f\n\x17mean_capture_efficiency\x18\x04 \x01(\x01\x12\x1e\n\x16mean_storage_integrity\x18\x05 \x01(\x01\x12\"\n\x1aminimum_capture_efficiency\x18\x06 \x01(\x01\x12!\n\x19minimum_storage_integrity\x18\x07 \x01(\x01\"\\\n\x19GenerateEsgReportResponse\x12\x12\n\nesg_report\x18\x01 \x01(\t\x12+\n\nstats_data\x18\x02 \x01(\x0b\x32\x17.esgReporting.StatsData2\xc6\x01\n\x10\x45sgReportService\x12L\n\tUploadCSV\x12\x1e.esgReporting.UploadCSVRequest\x1a\x1f.esgReporting.UploadCSVResponse\x12\x64\n\x11GenerateEsgReport\x12&.esgReporting.GenerateEsgReportRequest\x1a\'.esgReporting.GenerateEsgReportResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADCSVREQUEST']._serialized_start=38
  _globals['_UPLOADCSVREQUEST']._serialized_end=78
  _globals['_UPLOADCSVRESPONSE']._serialized_start=80
  _globals['_UPLOADCSVRESPONSE']._serialized_end=132
  _globals['_GENERATEESGREPORTREQUEST']._serialized_start=134
  _globals['_GENERATEESGREPORTREQUEST']._serialized_end=183
  _globals['_STATSDATA']._serialized_start=186
  _globals['_STATSDATA']._serialized_end=419
  _globals['_GENERATEESGREPORTRESPONSE']._serialized_start=421
  _globals['_GENERATEESGREPORTRESPONSE']._serialized_end=513
  _globals['_ESGREPORTSERVICE']._serialized_start=516
  _globals['_ESGREPORTSERVICE']._serialized_end=714
# @@protoc_insertion_point(module_scope)
